### ISSUE TITLE
parser crash

### ISSUE THREAD

**Issue by gurgeous** [tmm1/ripper-tags#83] opened 2018-03-18 17:58 UTC
I am the author of a brand new VS code extension called Bust A Gem - https://marketplace.visualstudio.com/items?itemName=gurgeous.bust-a-gem. Bust A Gem uses ripper-tags to create a TAGS file and power Go To Definition. Thanks for creating ripper-tags! I'm excited to see how people use the extension and ripper-tags together.

I have my first official report of ripper-tags crashing on input. Something in devise 4.4.1, see below. Let me know if you need more help diagnosing. One suggestion - would it be possible for ripper-tags to output a bit more information when it crashes, like the current file/position/line? I think that would be very helpful.

```
ripper-tags -f TAGS -R devise-4.4.1
```

```
Traceback (most recent call last):
43: from ruby/bin/ripper-tags:23:in `<main>'
42: from ruby/bin/ripper-tags:23:in `load'
41: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/bin/ripper-tags:15:in `<top (required)>'
40: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:177:in `process_args'
39: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:80:in `option_parser'
38: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:80:in `new'
37: from ruby/lib/ruby/2.5.0/optparse.rb:1062:in `initialize'
36: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:172:in `block in option_parser'
35: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:190:in `block in process_args'
34: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:190:in `call'
33: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:208:in `run'
32: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/emacs_formatter.rb:28:in `with_output'
31: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/default_formatter.rb:52:in `with_output'
30: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/default_formatter.rb:52:in `open'
29: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/default_formatter.rb:53:in `block in with_output'
28: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/emacs_formatter.rb:30:in `block in with_output'
27: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags.rb:209:in `block in run'
26: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:133:in `each_tag'
25: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:84:in `each_file'
24: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:98:in `each_input_file'
23: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:98:in `each'
22: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:85:in `block in each_file'
21: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
20: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `each'
19: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:63:in `block in resolve_file'
18: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
17: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `each'
16: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:63:in `block in resolve_file'
15: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
14: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `each'
13: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:63:in `block in resolve_file'
12: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
11: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `each'
10: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:63:in `block in resolve_file'
 9: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
 8: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:59:in `each'
 7: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:63:in `block in resolve_file'
 6: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:69:in `resolve_file'
 5: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:136:in `block in each_tag'
 4: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:165:in `tag_extractor'
 3: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/data_reader.rb:165:in `new'
 2: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/parser.rb:322:in `initialize'
 1: from ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/parser.rb:347:in `process'
ruby/lib/ruby/gems/2.5.0/gems/ripper-tags-0.5.1/lib/ripper-tags/parser.rb:444:in `on_defs': wrong number of arguments (given 4, expected 3) (ArgumentError)
```

**Comment by gurgeous** [comment] 2018-03-18 19:25
It's crashing on a template file, which isn't Ruby. Can we detect and avoid this case?

```
devise-4.4.1/lib/generators/active_record/templates/migration_existing.rb
```

```ruby
# frozen_string_literal: true

class AddDeviseTo<%= table_name.camelize %> < ActiveRecord::Migration<%= migration_version %>
  def self.up
    change_table :<%= table_name %> do |t|
<%= migration_data -%>

<% attributes.each do |attribute| -%>
      t.<%= attribute.type %> :<%= attribute.name %>
<% end -%>

      # Uncomment below if timestamps were not included in your original model.
      # t.timestamps null: false
    end

    add_index :<%= table_name %>, :email,                unique: true
    add_index :<%= table_name %>, :reset_password_token, unique: true
    # add_index :<%= table_name %>, :confirmation_token,   unique: true
    # add_index :<%= table_name %>, :unlock_token,         unique: true
  end

  def self.down
    # By default, we don't want to make any assumption about how to roll back a migration when your
    # model already existed. Please edit below which fields you would like to remove in this migration.
    raise ActiveRecord::IrreversibleMigration
  end
end
```

**Comment by gurgeous** [comment] 2018-03-18 19:27
I suppose I could just run ripper-tags with --force to make things easier for users. We'll never get ripper-tags bug reports, though :)

**Comment by mislav** [comment] 2018-03-22 10:33
Thanks for reporting. See https://github.com/tmm1/ripper-tags/pull/72

Some `.rb` files are ERB and therefore not valid Ruby. I'm not sure what we should do in this case. Do you have any suggestions for better error handling?

**Comment by gurgeous** [comment] 2018-03-22 15:07
Thanks for the response. Probably at a minimum we should do the following when an exception is thrown - print the file being processed and the current line number. That would make it easier to track down problems.

Also, can we detect that the file is invalid ruby? Does Ripper notice that the file is invalid somehow?

**Comment by mislav** [comment] 2018-03-23 12:31
> Also, can we detect that the file is invalid ruby? Does Ripper notice that the file is invalid somehow?

The problem is that `<` and `%` are valid operators in Ruby. Therefore, an ERB file that has Ruby code in it together with `<% ... %>` ERB blocks can theoretically parse as valid Ruby program, but then ripper-tags chokes on nonsense AST.

I think we should maybe forgive such crashes (i.e. allow ripper-tags to continue generating tags) in individual files as long as some other files were successfully processed. Perhaps ripper-tags could exit with a special non-zero status code that indicates that there were *some* errors but that the tags file was still generated, and warning messages on stderr could reflect the same. This would improve integration with tools such as yours.

> when an exception is thrown - print the file being processed and the current line number.

That sounds like a good idea. Would you be able to try to make a PR for that?

**Comment by gurgeous** [comment] 2018-03-23 15:03
I'd be happy to help! I'll take a stab at it when I get a chance. Any pointers you can offer re: error printing would be greatly appreciated. :)

**Comment by mislav** [comment] 2018-03-23 19:39
This is how ripper-tags works right now: https://github.com/tmm1/ripper-tags/blob/bf7c622d11bfbc2efcd7eec8de0d35f58391039c/lib/ripper-tags.rb#L206-L218

It's pretty straightforward. Error handling would have to get a tad more sophisticated if we were to achieve what we just planned out.

**Comment by gurgeous** [comment] 2018-03-24 16:14
Perhaps something like this:

1. If an error occurs, DataReader will print the filename. Showing the line # looks challenging... Maybe just dump the current sexp?
1. If we haven't output any tags yet, re-raise. Otherwise continue.
1. At the end, RipperTags.run can ask DataReader if it encountered any errors and exit(2) to indicate that things were imperfect.

Behavior is different with --force. Don't raise any errors and always exit with 0. This is as before, I think. Should we even bother to print an error in this case?

**Comment by mislav** [comment] 2018-12-11 10:17
This behavior is better after your contributions in https://github.com/tmm1/ripper-tags/pull/85#issuecomment-377489598, so I'm going to close this. Thank you!

**Closed by mislav** 2018-12-11 10:17 UTC
